name: zaplab_design
description: "UI Widget library for Nostr Apps"
version: 0.0.1
homepage: null

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  gap: ^3.0.1
  go_router: ^14.6.2
  sliver_tools: ^0.2.5
  tap_builder: ^0.5.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Courier-Prime
      fonts:
        - asset: lib/fonts/Courier-Prime.ttf
    - family: Zaplab-Icons
      fonts:
        - asset: lib/fonts/Zaplab-Icons.ttf
    - family: Inter
      fonts:
        - asset: lib/fonts/InterVariable.ttf
    - family: Lora
      fonts:
        - asset: lib/fonts/Lora[wght].ttf
